#https://github.com/blackmatrix7/ios_rule_scrip
---
port: 7890
socks-port: 7891
allow-lan: true
mode: rule
log-level: silent
external-controller: 0.0.0.0:9090
proxy-groups:
  - name: "自动选择"
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50
    proxies:
      - "ss.lyhepj.cn-hysteria"
  - name: "手动切换"
    type: select
    proxies:
      - "ss.lyhepj.cn-hysteria"
      - "节点选择"
      - "自动选择"
      - DIRECT
      - REJECT
  - name: "节点选择"
    type: select
    proxies:
      - "ss.lyhepj.cn-hysteria"
      - "自动捕获"
      - "手动采集"
  - name: steam-rule
    type: select
    proxies:
      - "自动选择"
      - "节点选择"
      - "手动切换"
      - DIRECT
  - name: "自动捕获"
    type: select
    use:
      - "高速机场"
    proxies:
      - "自动选择"
      - "节点选择"
      - "手动切换"
      - DIRECT
  - name: "手动采集"
    type: select
    use:
      - "手动提取"
    proxies:
      - "自动选择"
      - "节点选择"
      - "手动切换"
      - DIRECT
  - name: game-rule
    type: select
    proxies:
      - "自动选择"
      - "节点选择"
      - "手动切换"
      - DIRECT
  - name: Pxy-rule
    type: select
    proxies:
      - "自动选择"
      - "节点选择"
      - "手动切换"
      - DIRECT
  - name: GlobalMedia-rule
    type: select
    proxies:
      - "自动选择"
      - "节点选择"
      - "手动切换"
      - DIRECT
  - name: TikTok-rule
    type: select
    proxies:
      - "自动选择"
      - "节点选择"
      - "手动切换"
      - DIRECT
  - name: Cloudflare-rule
    type: select
    proxies:
      - "自动选择"
      - "节点选择"
      - "手动切换"
      - DIRECT
  - name: Developer-rule
    type: select
    proxies:
      - "自动选择"
      - "节点选择"
      - "手动切换"
      - DIRECT
  - name: "漏网之鱼"
    type: select
    proxies:
      - "自动选择"
      - "节点选择"
      - "手动切换"
      - DIRECT
rule-providers:
  steam:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Steam/Steam.yaml
    path: "./rule_provider/steam.yaml"
    interval: 86400
  steamCN:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/SteamCN/SteamCN.yaml
    path: "./rule_provider/steamCN.yaml"
    interval: 86400
  GameAll:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Game/Game.yaml
    path: "./rule_provider/GameAll.yaml"
    interval: 86400
  AdvertisingLite:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/AdvertisingLite/AdvertisingLite_Classical.yaml
    path: "./rule_provider/AdvertisingLite_Classical.yaml"
    interval: 86400
  lan:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Lan/Lan.yaml
    path: "./rule_provider/lan.yaml"
    interval: 86400
  download:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Download/Download.yaml
    path: "./rule_provider/download.yaml"
    interval: 86400
  github:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/GitHub/GitHub.yaml
    path: "./rule_provider/guthub.yaml"
    interval: 86400
  microsoft:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Microsoft/Microsoft.yaml
    path: "./rule_provider/microsoft.yaml"
    interval: 86400
  google:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Google/Google.yaml
    path: "./rule_provider/google.yaml"
    interval: 86400
  GlobalMedia:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/GlobalMedia/GlobalMedia_Classical.yaml
    path: "./rule_provider/GlobalMedia.yaml"
    interval: 86400
  china:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/ChinaMax/ChinaMax_Classical_No_IPv6.yaml
    path: "./rule_provider/china.yaml"
    interval: 86400
  custom:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/Viknopx/ruleNetwork@main/clash/rule/custom.yaml
    path: "./rule_provider/custom.yaml"
    interval: 86400
  customPxy:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/Viknopx/ruleNetwork@main/clash/rule/customPxy.yaml
    path: "./rule_provider/customPxy.yaml"
    interval: 86400
  DirectList:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Direct/Direct.yaml
    path: "./rule_provider/Direct.yaml"
    interval: 86400
  PxyList:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Global/Global_Classical.yaml
    path: "./rule_provider/Proxy_Classical.yaml"
    interval: 86400
  TikTok:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/TikTok/TikTok.yaml
    path: "./rule_provider/TikTok.yaml"
    interval: 86400
  Cloudflare:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Cloudflare/Cloudflare.yaml
    path: "./rule_provider/Cloudflare.yaml"
    interval: 86400
  Developer:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Developer/Developer.yaml
    path: "./rule_provider/Developer.yaml"
    interval: 86400
rules:
  - DST-PORT,7895,REJECT
  - DST-PORT,7892,REJECT
  - RULE-SET,AdvertisingLite,REJECT
  - RULE-SET,lan,DIRECT
  - RULE-SET,china,DIRECT
  - RULE-SET,custom,DIRECT
  - RULE-SET,DirectList,DIRECT
  - RULE-SET,steamCN,DIRECT
  - IP-CIDR,198.18.0.1/16,REJECT,no-resolve
  - RULE-SET,steam,steam-rule
  - RULE-SET,GameAll,game-rule
  - RULE-SET,github,Pxy-rule
  - RULE-SET,microsoft,Pxy-rule
  - RULE-SET,GlobalMedia,GlobalMedia-rule
  - RULE-SET,customPxy,Pxy-rule
  - RULE-SET,PxyList,Pxy-rule
  - RULE-SET,TikTok,TikTok-rule
  - RULE-SET,Cloudflare,Cloudflare-rule
  - RULE-SET,Developer,Developer-rule
  - MATCH,漏网之鱼
